import kotlin.jvm.optionals.getOrNull

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */
plugins {
  // Required plugins
  alias(libs.plugins.io.uoxx3.environment)
  alias(libs.plugins.io.gradle.nexus.publish)
}

allprojects {
  // Ignore root project
  if (this == rootProject) return@allprojects
  
  // Common plugins
  apply(plugin = "io.github.uoxx3.project-environment")
  apply(plugin = "org.gradle.maven-publish")
  apply(plugin = "org.gradle.signing")
}

nexusPublishing {
  repositories {
    sonatype {
      // Configure Maven-Central Sonatype account
      stagingProfileId.set(projectEnv["OSSRH_SONATYPE_PROFILE_ID"].getOrNull())
      username.set(projectEnv["OSSRH_SONATYPE_USERNAME"].getOrNull())
      password.set(projectEnv["OSSRH_SONATYPE_PASSWORD"].getOrNull())
    }
  }
}